### ISSUE TITLE
Add external log for errors

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#111]
Add more details to errors and log them using a service like [Papertrail](https://papertrailapp.com/).

**Comment by AdamVig** [comment]
- [x] Send logs to PaperTrail, invite Emmanuel to see them
- [x] Add human-readable logs
- [x] Add actual error causes to log output instead of only friendly error messages

**Comment by AdamVig** [comment]
[thlorenz/bunyan-format](https://github.com/thlorenz/bunyan-format) seems like a good choice for formatting output within the application (not relying on an external CLI), but it does not seem to support writing to a file. Writing to a file is important for PaperTrail's `remote_syslog` to work as simply as possible while maintaining a local copy of logs.

**Comment by AdamVig** [comment]
The current logging setup is this: Bunyan logs JSON objects at the "trace" level to a file called `stockpile-api.log`. On the server, a tool called `remote_syslog` sends those logs to PaperTrail.

The problem with this is that the logs are not human-readable. Having structured logging is great in general, because we could use those structured logs for monitoring and tracking purposes, but they are not good for quick troubleshooting. 

A good solution would be the following:
- keep the current setup the same
- add another logging stream that outputs logs at the "info" level, made human-readable using [bunyan-format](https://github.com/thlorenz/bunyan-format), to stdout and sends them to PaperTrail via [pm2-papertrail](https://github.com/haremo/pm2-papertrail)

**Comment by AdamVig** [comment]
Forgot to improve the actual error output from the app. Currently, it will output `500 Internal Server Error` to the application logs, but not the actual cause of that error. This can be implemented by adding a log output in the endpoint service's `handleError` function.

**Comment by AdamVig** [comment]
Remote logging of the new human-readable log stream works. I added a new search for the stream:
![image](https://cloud.githubusercontent.com/assets/5354752/24106313/defa96b4-0d5d-11e7-9b66-13e345f93887.png)

The problem I am facing now is related to pm2, our process manager. When I try to start the app, I get flooded with `EADDRINUSE` errors. It seems like pm2 is unaware that it is already running a copy of the app, so when it tries to run it again, it causes this flood of errors. This problem will make the human-readable logs unusable until it is fixed.

**Comment by AdamVig** [comment]
Opened #132 to fix deployment so that the human readable logs will be usable.
