### ISSUE TITLE
Fix id property name for brand, model and category

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#118]
`GET /brand` returns an object with the id in the `brandID` property, but the object returned by `PUT /brand` returns the id under the `id` property. This should be changed to `brandID`, `modelID` and `categoryID` to be consistent with the other objects returned by the API.

**Comment by AdamVig** [comment]
This happens because when a new item is created, the database returns only the ID of that new item. Since `endpoint.create()` does not know the primary key of the table is is creating a row in, it cannot easily return the correct property name for the returned ID.

The only way to fix this is to implement functionality similar to `endpoint.update()`, where the newly created row is found in the database and returned in full (instead of just returning the ID).

**Comment by AdamVig** [comment]
The problem with attempting to implement the aforementioned functionality in the creation function is that even though it has the ID of the created row, it does not know what column to look for the ID in.

This could be fixed by adding the name of the ID column of the table as a parameter of `endpoint.create()`. This could cause some confusion because the `columnName` parameter in all of the other database service functions does not need to represent the ID column, but this parameter would have to only be the name of the ID column.

**Comment by emroussel** [comment]
If it's too complicated, you can leave it as it is as long as it gets documented in the docs.

**Comment by AdamVig** [comment]
Closing in favor of documenting the current pattern.
