### ISSUE TITLE
Add token expiration

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#173]
Includes setting a time after which the token will be invalid and an endpoint to get a new token if it is about to expire.

**Comment by AdamVig** [comment]
Need to research how long expiration usually is.

**Comment by AdamVig** [comment]
Can be implemented easily with `passport-jwt`, see [this StackOverflow answer](http://stackoverflow.com/a/42089423/1850656).

Fifteen minutes seems like a safe bet for expiration time based on [this answer](https://security.stackexchange.com/a/119392). The logic behind this is that if a user is deleted or a user's role is changed, the token will also need to be updated. A user can wait fifteen minutes for this to propagate into his or her token, but waiting a week would be unreasonable.

With OAuth, it is typical to issue refresh tokens that can be used to get a new token when the existing one expires. With our non-OAuth approach, it would be better for the token to never expire. This would require an endpoint that can extend the expiration of the token or provide a new token, given a currently valid token.

See [this answer by an Auth0 employee](http://stackoverflow.com/a/26834685/1850656) for some background. In this answer, a distinction is made between web apps and mobile apps. In web apps, it is acceptable UX to login again after a period of inactivity. In mobile apps, the user should never have to log in again.

Since we are focused on our mobile app, we should go with the latter approach and use refresh tokens. [This is a good example](https://blog.hyphe.me/using-refresh-tokens-for-permanent-user-sessions-in-node/). The flow would look like this:
1. authenticate, get short-lived access token and long-lived refresh token in response
2. store both tokens in the UI, use access token with each request
3. on a request, when access token expires, use refresh token to get a new access token, then try request again

**Comment by AdamVig** [comment]
@emmanuelroussel check out the three steps I outlined above and see if they make sense for you to implement in the UI.

It will require some finesse to make the process of getting a new token seamless, so that the user can't tell that anything was different about that specific request.

**Comment by emroussel** [comment]
Yes that makes sense! What kind of error will it return when the token expires so that the app knows when to request a new one?

**Comment by AdamVig** [comment]
Good. It would be `401 Unauthorized`.

I was thinking that the error would have to contain some detail about the fact that it is related to a token expiration, but I think that can be inferred.

The only other place where the API would return a `401 Unauthorized` is `/auth`, where it would be saying that the username and password combination is invalid. I just changed the other `401 Unauthorized` errors, which are returned when the user does not have the correct role to access an entity, to `403 Forbidden` errors in #184.

With that in mind, you know that if you are hitting any role other than `/auth` and you get a `401 Unauthorized`, it means that the token is expired.

**Comment by emroussel** [comment]
Ok perfect!
