### ISSUE TITLE
Return created or updated entity in response

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#262]
*Edited by @adamvig to add task list.*

- [x] Change db.create to take a column parameter so it can build a where clause for finding the created row
- [x] Update everything that calls db.create (probably just endpoint.create) to include a column parameter
- [x] Update all calls to endpoint.create to include a column parameter
- [x] Add a resModify parameter to db.create and db.update for modifying the second query in each of those functions
- [x] Add a resModify parameter to endpoint.create and endpoint.update
- [x] Add a resModify parameter with a function that is used to modify get queries in any controllers that have a function used to modify get queries
- [x] Update tests for db.create, db.update, endpoint.create, endpoint.update, and endpoint.addAllMethods

**Comment by AdamVig** [comment]
Responses should be in the same format as the response from the `GET` endpoint of the same entity. Should be able to use the query modifier functions from the `GET` endpoint in order to easily get the same exact format as the `GET` response.

**Comment by AdamVig** [comment]
`endpoint.create` currently returns the ID of the created entity.
`endpoint.update` returns the entire updated entity, but not necessarily in the same format as the response from the `GET` endpoint of that same entity.

A potential solution is to accept an optional function parameter in `endpoint.create` and `endpoint.update` that is a query modification function intended for use with `endpoint.get`. That function could then be used when getting the created or updated entity back from the database in order to return it in the response.

The only drawback to this approach is that it further clutters the parameters of the methods on the endpoint service. Eventually, it may make sense to expose a single delegator function from the endpoint service like `delegate(action, tableName, columnName, {params})`, with `{params}` being an object containing params that relate to the method referred to by `action`. Since the `getAll` function doesn't need a `columnName` but does need `{params}`, those two parameters may need to switch places.
