### ISSUE TITLE
Fix password in /auth

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#59]
Currently, any password is considered as valid to log in.

**Comment by AdamVig** [comment]
The problem is in `./controllers/auth.js` `module.exports.authenticate`. The first `.then()` in the promise returns an array with the organization ID and the `bcrypt` comparison function.

The problem is that the next step of the promise checks `if (valid)`, which means that it is a truthy check instead of a strict boolean `true` check. Since the result of `bcrypt.compare(...)` is a promise, it is truthy and a token is sent.

To fix this, change the name of `valid` in the destructuring and use it as a promise. To prevent future problems like this, use `valid === true` in the conditional instead of just `if (valid)`.
