### ISSUE TITLE
Fix token validation

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#73]
If I register a new organization and use the token in the response to do a request, it returns `401 Unauthorized`. If I use the token returned by `/auth` to do a request, I receive a 500 with `"message": "Undefined binding(s) detected when compiling FIRST query: select * from organization where organizationID = ? limit ?"`.

I think from what we said, `/register` should not return a token, so that would solve the first part of the issue, but there seems be something wrong with the token (either in creating it or getting info from it).

I receive the same error whether I do the request from postman or from the app.

**Comment by AdamVig** [comment]
The `/auth` endpoint has been making tokens incorrectly. The tokens it has been making have been lacking the `sub` (subject) property, which contains the ID of the organization. The reason for this is on [this line of code](https://github.com/AdamVig/stockpile-api/blob/master/controllers/auth.js#L27), where the old, snake-case column name for the organization ID is used instead of the new, camelcase column name.

Changing this line of code to use the new column name should fix the problem. Adding error handling in #66 should help avoid problems like this in the future.
