### ISSUE TITLE
Change rentalID to tag to return items

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#94]
To delete a rental (return an item), the front end has to call `DELETE /rental/:rentalID`, but it should be `DELETE /rental/:itemTag`.

**Comment by AdamVig** [comment]
I will implement this for all `/rental` methods.

**Comment by AdamVig** [comment]
Since `tag` is not saved in the `rental` table, this table will need to be joined with the `item` table in order to get the `tag` column:

`SELECT rental.*, item.tag FROM rental JOIN item USING(item_id)`

This depends on #100, which will add the ability to use the endpoint service while also adding endpoint-specific joins to queries.

**Comment by AdamVig** [comment]
This will create a problem for the future when we add rental history (#53), because a `tag` will no longer uniquely identify a rental.
