### ISSUE TITLE
Check if item is rented before creating rental

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#96]
Right now, items that are rented can be rented multiple times

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/96/75de7ac9-4433-46e3-83ff-643536c63c9c/cdde7669-7128-4960-b73d-d2af17bbf22b) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/96/75de7ac9-4433-46e3-83ff-643536c63c9c/cdde7669-7128-4960-b73d-d2af17bbf22b) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by AdamVig** [comment]
I sort of fixed this by making `rental.itemID` a unique key. What error would you want me to return in this situation?

**Comment by emroussel** [comment]
Maybe something like: `Cannot rent item, item is already rented`

**Comment by AdamVig** [comment]
Currently, the endpoint returns:
```JSON
{
    "code": "ConflictError",
    "message": "a row with this id already exists"
}
```

Since error handling currently happens in the database service, using custom error messages will require passing them from the endpoint, through the endpoint service, to the database service. This will require adding more parameters to all of the functions involved.

As an alternative, it would make sense to create  a `messages` object that contains messages to return for create, delete, conflict, missing, and bad request. This object would have defaults set in the endpoint service, but could be overridden on a per-endpoint basis to provide relevant messages.

It would also be better to handle database errors in the endpoint service, as a way to promote separation of concerns. Currently, the database service returns Restify errors, which does not make much sense if it is being used internally. Instead, the endpoint service should return those high-level HTTP errors, while the database service should return low-level MySQL errors. This would remove the need of passing the `messages` object from the endpoint service to the database, which would help reduce the number of parameters being passed between the two services.
